version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: mercadolibre-tracer:V.001.001.03122020
    container_name: mercadolibre-container
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "1001:1001"