openapi: 3.0.0
info:
  title: MercadoLibre Tracing IP
  description: Servicio RESTful para el traceo de IPs maliciosas
  version: '1.0'
servers:
  - url: 'http://localhost:1001'
tags: 
- name: "trace-controller"
  description: "Métodos pertinences al traceo de IPs maliciosas"
paths:
  /trace:
    post:
      tags:
      - "trace-controller"
      summary: "Obtiene información de la IP invocando APIs externas. Retorna la informacion y luego persiste "
      operationId: "postIP"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "RequestDTO"
        schema:
        description: "IP en formato JSON que va a ser traceada"
        required: true
        example:
            ip: "7.4.103.255"

    responses:
        '201':
          description: Devuelve un ResponseTraceDTO con la informacion correspondiente
          content:
            application/json:
              schema:
                type: ResponseTraceDTO
                properties:
                  date:
                    type: string
                  times:
                    type: array
                    items:
                      type: string
                  languages:
                    type: array
                    items:
                      type: string
                  countryCode:
                    type: string
                  ip:
                    type: string
                  countryName:
                    type: string
                  estimatedDistance:
                    type: string
                  currencies:
                    type: array
                    items:
                      type: string
              examples:
                '0':
                  value: >-
                    {"ip":"7.4.103.255","countryName":"United States of
                    America","countryCode":"US","date":"2020-12-10","languages":["English
                    (en)"],"currencies":["USD (1USD = 0.827
                    EUR)"],"times":["04:49:57 (UTC-12:00)","05:49:57
                    (UTC-11:00)","06:49:57 (UTC-10:00)","07:49:57
                    (UTC-09:00)","08:49:57 (UTC-08:00)","09:49:57
                    (UTC-07:00)","10:49:57 (UTC-06:00)","11:49:57
                    (UTC-05:00)","12:49:57 (UTC-04:00)","02:49:57
                    (UTC+10:00)","04:49:57
                    (UTC+12:00)"],"estimatedDistance":"8701 km"}
    servers:
        - url: 'http://localhost:1001'
